import {Manrope} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const ManropeFont  = Manrope({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${ManropeFont.className} h-full antialiased`}
    >
      <body >
        <Navbar> </Navbar>
        {children}
        <Footer> </Footer>
        </body>
    </html>
  );
}
