import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const ManropeFont = Manrope({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body className="className={`${ManropeFont.className} h-full antialiased`}">
        <Navbar />
        {children}
       
        <Footer />
         <Toaster position="top-right"/> 
      </body>
    </html>
  );
}
